apiVersion: apps/v1
kind: Deployment
metadata:
  name: heiweo01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heiweo01
  template:
    metadata:
      labels:
        app: heiweo01
    spec:
      containers:
      - image: okteto.dev/heiweo01:latest
        name: heiweo01
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3fadb19b-abb8-4a21-90fb-bfd9fd9a7a71"
        - name: Vless_Path
          value: "/vl555oreiero3432"
        - name: Vmess_UUID
          value: "3fadb19b-abb8-4a21-90fb-bfd9fd9a7a71"
        - name: Vmess_Path
          value: "/vm666iweiwngoi2343"
        - name: Share_Path
          value: "/v2link"
