apiVersion: v1
kind: Service
metadata:
  name: heiweo01
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "heiweo01"
    port: 8080
  selector:
    app: heiweo01
